/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportRuleIdRouteImport } from './routes/report.$ruleId'
import { Route as ApiRulesRouteImport } from './routes/api/rules'
import { Route as ApiLogsRouteImport } from './routes/api/logs'
import { Route as ApiInteractionsRouteImport } from './routes/api/interactions'
import { Route as AiLogRuleIdRouteImport } from './routes/ai-log.$ruleId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRuleIdRoute = ReportRuleIdRouteImport.update({
  id: '/report/$ruleId',
  path: '/report/$ruleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRulesRoute = ApiRulesRouteImport.update({
  id: '/api/rules',
  path: '/api/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogsRoute = ApiLogsRouteImport.update({
  id: '/api/logs',
  path: '/api/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInteractionsRoute = ApiInteractionsRouteImport.update({
  id: '/api/interactions',
  path: '/api/interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLogRuleIdRoute = AiLogRuleIdRouteImport.update({
  id: '/ai-log/$ruleId',
  path: '/ai-log/$ruleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/ai-log/$ruleId': typeof AiLogRuleIdRoute
  '/api/interactions': typeof ApiInteractionsRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/rules': typeof ApiRulesRoute
  '/report/$ruleId': typeof ReportRuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/ai-log/$ruleId': typeof AiLogRuleIdRoute
  '/api/interactions': typeof ApiInteractionsRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/rules': typeof ApiRulesRoute
  '/report/$ruleId': typeof ReportRuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/ai-log/$ruleId': typeof AiLogRuleIdRoute
  '/api/interactions': typeof ApiInteractionsRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/rules': typeof ApiRulesRoute
  '/report/$ruleId': typeof ReportRuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/ai-log/$ruleId'
    | '/api/interactions'
    | '/api/logs'
    | '/api/rules'
    | '/report/$ruleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/ai-log/$ruleId'
    | '/api/interactions'
    | '/api/logs'
    | '/api/rules'
    | '/report/$ruleId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/ai-log/$ruleId'
    | '/api/interactions'
    | '/api/logs'
    | '/api/rules'
    | '/report/$ruleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  AiLogRuleIdRoute: typeof AiLogRuleIdRoute
  ApiInteractionsRoute: typeof ApiInteractionsRoute
  ApiLogsRoute: typeof ApiLogsRoute
  ApiRulesRoute: typeof ApiRulesRoute
  ReportRuleIdRoute: typeof ReportRuleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$ruleId': {
      id: '/report/$ruleId'
      path: '/report/$ruleId'
      fullPath: '/report/$ruleId'
      preLoaderRoute: typeof ReportRuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rules': {
      id: '/api/rules'
      path: '/api/rules'
      fullPath: '/api/rules'
      preLoaderRoute: typeof ApiRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logs': {
      id: '/api/logs'
      path: '/api/logs'
      fullPath: '/api/logs'
      preLoaderRoute: typeof ApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interactions': {
      id: '/api/interactions'
      path: '/api/interactions'
      fullPath: '/api/interactions'
      preLoaderRoute: typeof ApiInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-log/$ruleId': {
      id: '/ai-log/$ruleId'
      path: '/ai-log/$ruleId'
      fullPath: '/ai-log/$ruleId'
      preLoaderRoute: typeof AiLogRuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  AiLogRuleIdRoute: AiLogRuleIdRoute,
  ApiInteractionsRoute: ApiInteractionsRoute,
  ApiLogsRoute: ApiLogsRoute,
  ApiRulesRoute: ApiRulesRoute,
  ReportRuleIdRoute: ReportRuleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
